export const productRows = [
    { id: 1, 
        name: 'HeadPhone', 
        photo: 'https://vetra.laborasyon.com/assets/images/products/1.jpg', 
        stock: 'In stock', 
        price: '499,900', 
        state: 'Lagos', 
        age: 35 
    },
    { id: 2, 
        name: 'Shoe', 
        photo: 'https://vetra.laborasyon.com/assets/images/products/2.jpg',
        stock: 'In stock', 
        price: '500,300',
        state: 'Abuja'
    },
    { id: 3, 
        name: 'Digital Clock', 
        photo: 'https://vetra.laborasyon.com/assets/images/products/3.jpg',
        stock: 'Out of Stock',
        price: '101,900', 
        state: 'Port Harcourt'
    },
    { id: 4, name: 'Toy Car', photo: 'https://vetra.laborasyon.com/assets/images/products/5.jpg', stock: 'In stock', price: '50,900', state: 'Ekiti'},
    { id: 5, name: 'Sun Glasses', photo: 'https://vetra.laborasyon.com/assets/images/products/6.jpg', stock: 'In stock', price: '50,900', state: 'Lagos' },
    { id: 6, name: 'Cake', photo: "https://vetra.laborasyon.com/assets/images/products/7.jpg", stock: 'Out of Stock', price: '10,500', state: 'Kwara' },
    { id: 7, name: 'Glass', photo: '	https://vetra.laborasyon.com/assets/images/products/9.jpg', stock: 'In stock', price: '70,200', state: 'Abia'},
    { id: 8, name: 'HeadPhone', photo: 'https://vetra.laborasyon.com/assets/images/products/10.jpg', stock: 'In stock', price: '870,500', state: 'Ekiti'},
    { id: 9, name: 'Perfume', photo: 'https://vetra.laborasyon.com/assets/images/products/4.jpg', stock: 'In stock', price: '170,500', state: 'Kaduna'},
    { id: 9, name: 'Perfume', photo: 'https://vetra.laborasyon.com/assets/images/products/8.jpg', stock: 'In stock', price: '170,500', state: 'Kaduna'},
];

export const userRows = [
    { 
      id: 1, 
      lastName: 'Snow', 
      firstName: 'Jon', 
      username: 'jonSnow112', 
      email: 'johnsnow@email.com', 
      state: 'Lagos', 
      status: "Inactive",
      avatar: "https://images.pexels.com/photos/7562313/pexels-photo-7562313.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"
    },
    { 
      id: 2, 
      lastName: 'Lannister',
      firstName: 'Cersei', 
      username: 'lannCerc', 
      email: 'johnsnow@email.com', 
      state: 'Abuja', 
      status: "Blocked",
      avatar: "https://images.pexels.com/photos/3671083/pexels-photo-3671083.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"
    },
    { id: 3, 
      lastName: 'Lannister', 
      firstName: 'Jaime', 
      username: 'jaimeLann', 
      email: 'johnsnow@email.com', 
      state: 'Port Harcourt', 
      status: "Active",
      avatar: "https://images.pexels.com/photos/6652928/pexels-photo-6652928.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
    },
    { id: 4, 
      lastName: 'Stark', 
      firstName: 'Arya', 
      username: 'arStark', 
      email: 'johnsnow@email.com', 
      state: 'Ekiti', 
      status: "Blocked",
      avatar: "https://images.pexels.com/photos/5384429/pexels-photo-5384429.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    },
    { id: 5, 
      lastName: 'Targaryen', 
      firstName: 'Daenerys', 
      username: 'jonSnow112', 
      email: 'johnsnow@email.com', 
      state: 'Lagos', 
      avatar: "https://images.pexels.com/photos/7204273/pexels-photo-7204273.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
      status: "Active"
    },
    { id: 6,
      lastName: 'Melisandre', 
      firstName: null, 
      username: 'jonSnow112', 
      email: 'johnsnow@email.com', 
      avatar: 'https://images.pexels.com/photos/3991140/pexels-photo-3991140.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500',
      state: 'Kwara', 
      age: 150 
    },
    { id: 7, lastName: 'Clifford', firstName: 'Ferrara', username: 'jonSnow112', email: 'johnsnow@email.com', state: 'Abia', age: 44 },
    { id: 8, lastName: 'Frances', firstName: 'Rossini', username: 'jonSnow112', email: 'johnsnow@email.com', state: 'Ekiti', age: 36 },
    { id: 9, lastName: 'Roxie', firstName: 'Harvey', username: 'jonSnow112', email: 'johnsnow@email.com', state: 'Kaduna', age: 65 },
];


export const ordeRows = [
    { id: "#3120", firstName: 'Jon', date: 'May 23,2021', price: '499,900', status: 'processing', age: 35 },
    { id: "#3121", firstName: 'Cersei', date: 'May 15,2021', price: '500,300', status: 'shipped', age: 42 },
    { id: "#3122", firstName: 'Jaime', date: 'Apr 24,2021', price: '101,900', status: 'completed', age: 45 },
    { id: "#3123", firstName: 'Arya', date: 'Apr 10,2021', price: '50,900', status: 'refunded', age: 16 },
    { id: "#3124", firstName: 'Daenerys', date: 'Mar 5,2021', price: '50,900', status: 'cancelled', age: null },
    { id: "#3125", firstName: null, date: 'May 23,2021', price: '10,500', status: 'processing', age: 150 },
    { id: "#3126", firstName: 'Ferrara', date: 'May 15,2021', price: '70,200', status: 'shipped', age: 44 },
    { id: "#3127", firstName: 'Rossini', date: 'Apr 24,2021', price: '870,500', status: 'completed', age: 36 },
    { id: "#3128", firstName: 'Harvey', date: 'Apr 10,2021', price: '170,500', status: 'refunded', age: 65 },
    { id: "#3129", firstName: 'Cookie', date: 'Mar 5,2021', price: '15,000', status: 'cancelled', age: 65 },
  ];